# Generated by Django 5.2.12 on 2026-03-17 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korok_net_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Наименование курса'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='korok_net_app.applications', verbose_name='Заявка'),
        ),
    ]
