# Generated by Django 5.2.12 on 2026-03-18 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korok_net_app', '0002_alter_applications_title_alter_reviews_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinformation',
            name='phone_num',
            field=models.CharField(max_length=12, unique=True, verbose_name='Номер телефона'),
        ),
    ]
