# Generated by Django 5.2.12 on 2026-03-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korok_net_app', '0003_alter_userinformation_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applications',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('in_process', 'Идет обучение'), ('finished', 'Обучение завершено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
