# Generated by Django 5.2.12 on 2026-03-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korok_net_app', '0004_alter_applications_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='mark',
            field=models.SmallIntegerField(choices=[(1, 'Очень плохо'), (2, 'Плохо'), (3, 'Удовлетворительно'), (4, 'Хорошо'), (5, 'Отлично')], verbose_name='Оценка'),
        ),
    ]
